STRATEGY_NAME = "S&P 500 Contrarian"
SYMBOL = 'SPY'
TRADING_CAPITAL = 10000.00
RISK_PERCENT = 2.0
BUY_THRESHOLD_PERCENT = 2.0
STOP_LOSS_PERCENT = 2.0
TAKE_PROFIT_PERCENT = 4.0
HOLDING_PERIOD_DAYS = 2
